name: Desplegament

on:
  workflow_run:
    workflows: ["Validacions"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branca a desplegar'
        required: false
        default: 'main'
        type: string

permissions:
  id-token: write # This is required for the tailscale action to request a JWT from GitHub
jobs:
  desplegament:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.event == 'pull_request')) }}
    
    steps:
      - name: Determinar branca a desplegar
        id: branch_selector
        shell: bash
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_BRANCH: ${{ github.event.inputs.branch }}
          RUN_HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          if [ "$EVENT_NAME" == "workflow_dispatch" ]; then
            echo "selected_branch=$INPUT_BRANCH" >> "$GITHUB_OUTPUT"
          else
            echo "selected_branch=$RUN_HEAD_BRANCH" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch_selector.outputs.selected_branch }}
          fetch-depth: 0
      
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Desplegar codi al robot
        uses: appleboy/ssh-action@v0.1.6
        env:
          BRANCH: ${{ steps.branch_selector.outputs.selected_branch }}
        with:
          host: ${{ secrets.PI_TAILSCALE_IP }}
          username: ${{ secrets.PI_USER }}
          password: ${{ secrets.PI_PASSWORD }}
          envs: BRANCH
          script: |
            set -e
            echo "Desplegant branca: $BRANCH"
            cd /home/arnau/picar-x-mnebot
            git fetch origin
            git checkout "$BRANCH"
            git pull origin "$BRANCH"
            echo "Codi desplegat correctament a la branca $BRANCH"
            sudo cp picarx.service /etc/systemd/system/picarx.service
            sudo systemctl daemon-reload
            sudo systemctl restart picarx.service
            sudo systemctl enable picarx.service
            echo "Robot en execuci√≥"
