name: Desplegament

on:
  workflow_run:
    workflows: ["Validacions"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branca a desplegar'
        required: false
        default: 'main'
        type: string

permissions:
  id-token: write # This is required for the tailscale action to request a JWT from GitHub
jobs:
  desplegament:
    runs-on: ubuntu-latest
    # Si s'executa manualment (workflow_dispatch), sempre executar
    # Si s'executa després de validacions (workflow_run), només si ha acabat amb èxit
    # I només per push a main o pull requests a main
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.event == 'pull_request')) }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Determinar branca a desplegar
        id: branch
        run: |
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
      
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Desplegar codi al robot
        uses: appleboy/ssh-action@v0.1.6
        env:
          BRANCH_PR: ${{ steps.branch.outputs.branch }}
        with:
          host: ${{ secrets.PI_TAILSCALE_IP }}
          username: ${{ secrets.PI_USER }}
          password: ${{ secrets.PI_PASSWORD }}
          envs: BRANCH_PR
          script: |
            echo "Desplegant branca: $BRANCH"
            cd /home/arnau/picar-x-mnebot
            git fetch origin
            git checkout -- "$BRANCH_PR"
            git pull origin "$BRANCH_PR"
            echo "Codi desplegat correctament a la branca $BRANCH_PR"
            # Copiar el fitxer de servei al directori systemd
            sudo cp picarx.service /etc/systemd/system/picarx.service
            sudo systemctl daemon-reload
            sudo systemctl restart picarx.service
            sudo systemctl enable picarx.service
            echo "Robot en execució"
